name: run-on-time
run-name: A cron job test
on:
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch:

jobs:
    print-stuff:
        runs-on: ubuntu-latest
        steps:
            - name: Setup
              uses: ./.github/actions/setup

            - name: Run the JS file
              run: node cron.js
