name: Email service
run-name: Send email to me
on:
    schedule:
        - cron: '5 0 * * *'
    workflow_dispatch:

jobs:
    send-mail:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Run the JS file
              env:
                  EMAIL: ${{ secrets.EMAIL }}
                  PASS: ${{ secrets.PASS }}
              run: node email.js
