name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    print-secret:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Setup npm
              uses: actions/setup-node@v3

            - name: Install Dependancies
              run: npm i

            - name: test run
              env:
                  TEST: ${{ secrets.ROUTE }}
              run: npm run run

    bashing-my-head:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              env:
                  TEST: ${{ secrets.TEST }}
              run: echo "$TEST"
